config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

# класс "Ограничение". М-д "matches" принимает запрос, который был отправлен
# на адрес '/admin/users'. Приходит на этот адрес запрос, перенаправлем в AdminConstraint
# проверку, читаем запрос, смотрим, от кого он и решаем: пускать или нет.
# "user_id" - помещен либо в сессию, либо в зашифрованные куки если юзер поставил галочку
# "запомнить меня" (см. authentication.rb)
# request.cookie_jar.encrypted[:user_id] - дешифровка куки
class AdminConstraint
  def matches?(request)
    user_id = request.session[:user_id] || request.cookie_jar.encrypted[:user_id]
    # является ли найденный юзер админом (если юзер найден)
    User.find_by(id: user_id)&.admin_role?
  end
end

Rails.application.routes.draw do
  # Смонтировать маршрут Sidekiq::Web , по какому адресу он будет доступен ('/sidekiq'),
  # т.е. подрубаем интерфейс sidekiq по адресу '/sidekiq' (http://127.0.0.1:3000/sidekiq)
  mount Sidekiq::Web => '/sidekiq', constraints: AdminConstraint.new

  resources :hashtags, only: :show, param: :text

  # API V1 (версия 1) routes
  namespace :api do
    namespace :v1 do
      resources :users, only: [], param: :username do
        resources :questions, only: :index
        resources :albums, except: %i[edit new]
      end

      resources :hashtags, only: :index
      resources :users, only: :index
    end
  end

  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    # Для любого юзера будет только одна сессия регистрации (!)
    resource :session, only: %i[new create destroy]

    resources :users do
      resources :albums do
        member do
          delete :delete_album_photos
        end
      end
    end

    resource :password_reset, only: %i[new create edit update]

    # Со страницы юзера будет отправляться форма на создание вопроса
    resources :questions, except: %i[show new]

    root 'users#index'

    # не будет существовать тогда маршрута для всех, кроме админа. Закрывается
    # доступ к пространству маршрутов admin
    namespace :admin do
      constraints(AdminConstraint.new) do
        resources :users, except: %i[new] do
          get :upvote, on: :member
          get :downvote, on: :member
        end
      end
    end

    # Синонимы путей — в дополнение к созданным в ресурсах выше.
    # get 'sign_up' => 'users#new'
    # get 'log_out' => 'sessions#destroy'
    # get 'log_in' => 'sessions#new'
  end
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  include Authorship

  belongs_to :user

  # рельсы добавят к нему `_id` и найдут нужное поле в таблице
  # валидация наличия объекта belongs_to происходит в случае,
  # если у этой связи не установлен ключ optional: true
  belongs_to :author,
             class_name: 'User',
             optional: true

  has_many :question_hashtags, dependent: :destroy
  has_many :hashtags, through: :question_hashtags

  validates :text, presence: true, length: { minimum: 1, maximum: 255 }

  validate :del, on: :destroy

  after_save_commit :create_hashtags

  # те вопросы, у которых поле "answer" не содержит nil
  scope :answered, -> { where.not(answer: nil) }
  # те вопросы, у которых поле "answer" содержит nil (не отвеченные)
  scope :unanswered, -> { where(answer: nil) }

  scope :sorted, -> { order(created_at: :desc) }

  scope :all_by_hashtags, lambda { |hashtags|
    questions = includes(:user)
    questions = if hashtags
                  # связка в SQL с таблице хэштегов, только если они существуют
                  questions.joins(:hashtags).where(hashtags: hashtags).preload(:hashtags)
                else
                  questions.includes(:question_hashtags, :hashtags)
                end
    # либо выбираем все вопросы
    questions.order(created_at: :desc)
  }

  private

  # выбираем любые 3 слова из вопроса в качестве хэштега,
  # содержащие от 4 до 20 букв
  def parse_hashtags(string)
    string.downcase.split
          .select { |i| i.chars.count.between?(4, 20) }
          .map { |i| i.delete('^a-zA-Zа-яА-Я-') }
          .uniq.sample(3)
  end

  # генератор хэштега (от анонима хэштеги не генерируюся)
  def create_hashtags
    return if author_id.nil?

    transaction do
      self.hashtags =
        parse_hashtags("#{text} #{answer}").map do |hashtag|
          Hashtag.create_or_find_by(text: "##{hashtag}")
        end
    end
  end

  def del
    return if hashtags.blank? || author_id.nil?

    self.hashtags = hashtags

    hashtags.destroy_all
  end
end

app/controllers/api/v1/questions_controller.rb
# frozen_string_literal: true

module API
  module V1
    class QuestionsController < RootController
      def index
        @user = User.where(username: params[:user_username]).take
        @questions = @user.questions
        success!(QuestionBlueprint.render_as_hash(@questions, view: :normal))
      end
    end
  end
end

app/controllers/questions_controller.rb
# frozen_string_literal: true

class QuestionsController < ApplicationController
  before_action :set_question!, only: %i[edit update destroy show]

  # Проверяем имеет ли юзер доступ к экшену для всей дествий, кроме задавания
  # вопроса, это действие может вызвать даже неавторизованный пользователь.
  before_action :authorize_user, except: %i[create index]

  # Проверяем, имеет ли пользователь право на выполнение запрошенного действия
  before_action :authorize_question!
  # М-д "verify_authorized" доступен из Pundit и он проверит, что мы в нашем "before_action"
  # проверили права доступа. Если проверены не были, то выскочит ошибка. Проверка во всех
  # действиях контроллера
  after_action :verify_authorized, except: %i[create index]

  def index
    @hashtags = Hashtag.where(id: params[:hashtag_ids]) if params[:hashtag_ids]
    @pagy, @questions = pagy Question.includes(%i[author question_hashtags])
                                     .all_by_hashtags(@hashtags)
    @questions = @questions.decorate
  end

  # GET /questions/1/edit
  def show; end

  # Действие create будет отзываться при POST-запросе по адресу /questions из
  # формы нового вопроса, которая находится в шаблоне на странице
  # /questions/edit
  # def create
  #   @question = Question.new question_params

  #   @question.author = current_user

  #   # Проверяем капчу вместе с сохранением вопроса. Если в капче была допущена
  #   # ошибка, она будет добавлена в ошибки @question.errors.
  #   if check_captcha(@question) && @question.save
  #     flash[:success] = t('.success')
  #     redirect_to user_path(@question.user)
  #   else
  #     # потому что "new" - шаблона нет
  #     render :edit
  #   end
  # end

  # обращаемся к output по ключу "question" (см. метод build_model)
  def edit; end

  # Действие update будет отзываться при PUT-запросе из формы редактирования
  # вопроса, которая находится по адресу /questions/:id, например, /questions/1
  #
  # Перед этим действием сработает before_action :load_questions и в переменной
  # @question у нас будет лежать вопрос с нужным id равным params[:id].
  def create
    Questions::Create.call(params: question_params,
                           current_user: current_user) do |m|
      m.failure :validation do |result|
        @question = result[:question]
        render :edit
      end

      # достаем в случае успеха:
      m.success do |result|
        redirect_to user_path(result[:question].user), success: t('.success')
      end
    end
  end

  # Действие destroy будет отзываться при DELETE-запросе со страницы
  # пользователя, которая находится по адресу /users/:id/show.
  #
  # Перед этим действием сработает before_action :load_questions и в переменной
  # @question у нас будет лежать вопрос с нужным id равным params[:id].
  def update
    if @question.update(question_params)
      flash[:success] = t('.success')
      redirect_to user_path(@question.user)
    else
      render :edit
    end
  end

  def destroy
    # Перед тем, как удалять вопрос, сохраним пользователя, чтобы знать, куда
    # редиректить после удаления.
    for_decorate(@question)

    user = @question.user

    # Удаляем вопрос
    @question.destroy

    # Отправляем пользователя на страницу адресата вопроса с сообщением
    flash[:success] = t('.success')
    redirect_to user_path(user)
  end

  private

  # Если загруженный из базы вопрос не пренадлежит и текущему залогиненному
  # пользователю — посылаем его с помощью описанного в контроллере
  # ApplicationController метода reject_user.
  def authorize_user
    reject_user unless @question.user == current_user
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_question!
    @question = Question.find(params[:id])
  end

  # Явно задаем список разрешенных параметров для модели Question. Мы говорим,
  # что у хэша params должен быть ключ :question. Значением этого ключа может
  # быть хэш с ключами: :user_id и :text. Другие ключи будут отброшены.
  def question_params
    # Защита от уязвимости: если текущий пользователь — адресат вопроса,
    # он может менять ответы на вопрос, ему доступно также поле :answer.
    if current_user.present? &&
       params[:question][:user_id].to_i == current_user.id
      params.require(:question).permit(:user_id, :text, :answer, hashtag_ids: [])
    else
      params.require(:question).permit(:user_id, :text)
    end
  end

  def for_decorate(resource)
    return unless resource.decorated?

    resource.object
  end

  def check_captcha(model)
    current_user.present? || verify_recaptcha(model: model)
  end

  # Нужно авторизовать конкретный вопрос или просто использовать модель. Т.е. если
  # вопрос есть, то мы делаем проверку относительно него. Если вопроса нет, то мы говорим
  # что юзер пытается делать что-то относительно ресурса вопроса.
  # Метод "authorize" доступен из Pundit, потому что в ApplicationController заинклюдили
  # concern "Authorization", а этот concern в свою очередь инклюдит Pundit
  def authorize_question!
    authorize(@question || Question)
  end
end

app/views/questions/_form.html.erb
<%# Форма для создания/правки вопроса %>
<div
  class="form">
  <%# Форма для объекта @question %>
  <%# <%= form_with(model: @question, url: questions_path) do |f| %>
    <%= form_for(@question) do |f| %>
      <%= render 'shared/errors', object: @question %>

      <%# Скрытое поле — айдишник юзера, кому задается вопрос %>
      <%= f.hidden_field :user_id %>

      <div class="form-field">
        <%= f.label :text, t('.question'), class: 'form-label' %>
        <%= f.text_area :text, class: 'form-textarea', readonly: (true if current_user.present?) %>
      </div>

      <%# Простая авторизация - может ли текущий юзер править вопрос? %>
      <% if current_user.present? && current_user == @question.user %>
        <div class="form-field">
          <%= f.label :answer, t('.answer'), class: 'form-label' %>
          <%= f.text_area :answer, class: 'form-textarea' %>
        </div>
      <% end %>

      <%= recaptcha_tags unless current_user.present? %>

      <div class="form-action buffer-both">
        <%= f.submit t('global.button.save'), class: 'button button-dark button-small' %>
        <%= link_to t('.return'), user_path(@question.user) %>
      </div>
    <% end %>
  </div>

app/views/questions/_question.html.erb
<%# Это фрагмет (паршал, partial) для вывода вопроса. В нем определена %>
<%# локальная переменная question, в которую при вызове будет передан %>
<%# как в метод ruby объект после ключа (object: @question) %>

<div class="question">
  <div class="question-content">

     <div class="text-small">
      <% author = question.author %>
      <%= author ? (link_to "@#{author.username}", author) : t('global.text.unknown') %>
    </div>

    <section class="card-header">
       <% if !author&.gravatar_hash.blank? && author.username != Dotenv.load('.env')['TEST_USERNAME'] %>
          <%= image_tag "https://www.gravatar.com/avatar/#{author&.gravatar_hash}.jpg?s=#{50}",
                    class: 'user-image', alt: '[Foto]' %>
       <% elsif author&.gravatar_hash.present? && author.username == Dotenv.load('.env')['TEST_USERNAME'] %>
          <%= image_tag 'Elizabeth.jpg', height: '80', width: '70',
                    class: 'user-image', alt: '[Foto]' %>
       <% else %>
          <%= image_tag 'avatar.jpg', size: '50',
                    class: 'user-image', alt: '[Foto]' %>
       <% end %>
    </section>

    <%# Текст вопроса %>
    <div class="card-body">
      <div class="question-text text-lead">
        <% if question.text.split.map { |str| str.chars.count }.max > 40 %>
          <p class="my-2">
            <%= truncate strip_tags(question.text), length: 40, omission: t('global.text.omission') %>
          </p>
        <% else %>
          <%= question.text %>
        <% end %>
      </div>

      <%# Текст ответа, если он есть %>
      <% if question.answer.present? %>
        <div class="question-answer text-lead">
          <% if question.answer.split.map { |str| str.chars.count }.max > 40 %>
            <p class="my-2">
              <%= truncate strip_tags(question.answer), length: 40, omission: t('global.text.omission') %>
            </p>
          <% else %>
            <%= question.answer %>
          <% end %>
        </div>
      <% end %>
    </div>

    <div class="question-text text-lead">
      <% question.hashtags.each do |hashtag| %>
        <%= link_to "#{hashtag.text}", hashtag_path(hashtag.text), class: 'hashtag' %>
      <% end %>
    </div>


    <%# Дата создания вопроса (отформатированная) %>
    <div class="question-date">
      <%= question.decorate.formatted_created_at %>
    </div>
  </div>

    <%# Определяем какая будет иконка, если у вопроса нет ответа, то иконка %>
    <%# ответа на письмо, иначе — карандашик %>
    <% edit_icon = question.answer.blank? ? 'reply' : 'pencil' %>
    <div class="question-actions">
      <% if policy(question).edit? %>
         <%= link_to fa_icon(edit_icon), edit_question_path(question) %>
      <% end %>
      <% if policy(question).destroy? %>
        <%= link_to fa_icon('trash-o'), question_path(question),
                  method: :delete, data: {confirm: t('global.dialog.you_sure')} %>
      <% end %>
    </div>
</div>

app/views/questions/edit.html.erb
<%# Страница редактирования вопроса %>
<% provide :page_title, t('.title') %>

<div class="container content-wrapper buffer-both">
  <h1 class="title-medium"><%= t('.theme') %></h1>

  <div class="column-1-2">
    <%# Подключаем паршиал app/views/questions/_form.html.erb %>
    <%= render 'form' %>
  </div>
</div>

app/views/questions/index.html.erb
<div class="buffer-both">
  <div class="questions-list buffer-both">
    <%= render @questions.includes([:hashtags]) %>
  <div>
</div>