config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

# класс "Ограничение". М-д "matches" принимает запрос, который был отправлен
# на адрес '/admin/users'. Приходит на этот адрес запрос, перенаправлем в AdminConstraint
# проверку, читаем запрос, смотрим, от кого он и решаем: пускать или нет.
# "user_id" - помещен либо в сессию, либо в зашифрованные куки если юзер поставил галочку
# "запомнить меня" (см. authentication.rb)
# request.cookie_jar.encrypted[:user_id] - дешифровка куки
class AdminConstraint
  def matches?(request)
    user_id = request.session[:user_id] || request.cookie_jar.encrypted[:user_id]
    # является ли найденный юзер админом (если юзер найден)
    User.find_by(id: user_id)&.admin_role?
  end
end

Rails.application.routes.draw do
  # Смонтировать маршрут Sidekiq::Web , по какому адресу он будет доступен ('/sidekiq'),
  # т.е. подрубаем интерфейс sidekiq по адресу '/sidekiq' (http://127.0.0.1:3000/sidekiq)
  mount Sidekiq::Web => '/sidekiq', constraints: AdminConstraint.new

  resources :hashtags, only: :show, param: :text

  # API V1 (версия 1) routes
  namespace :api do
    namespace :v1 do
      resources :users, only: [], param: :username do
        resources :questions, only: :index
        resources :albums, except: %i[edit new]
      end

      resources :hashtags, only: :index
      resources :users, only: :index
    end
  end

  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    # Для любого юзера будет только одна сессия регистрации (!)
    resource :session, only: %i[new create destroy]

    resources :users do
      resources :albums do
        member do
          delete :delete_album_photos
        end
      end
    end

    resource :password_reset, only: %i[new create edit update]

    # Со страницы юзера будет отправляться форма на создание вопроса
    resources :questions, except: %i[show new]

    root 'users#index'

    # не будет существовать тогда маршрута для всех, кроме админа. Закрывается
    # доступ к пространству маршрутов admin
    namespace :admin do
      constraints(AdminConstraint.new) do
        resources :users, except: %i[new] do
          get :upvote, on: :member
          get :downvote, on: :member
        end
      end
    end

    # Синонимы путей — в дополнение к созданным в ресурсах выше.
    # get 'sign_up' => 'users#new'
    # get 'log_out' => 'sessions#destroy'
    # get 'log_in' => 'sessions#new'
  end
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  include Authorship

  belongs_to :user

  # рельсы добавят к нему `_id` и найдут нужное поле в таблице
  # валидация наличия объекта belongs_to происходит в случае,
  # если у этой связи не установлен ключ optional: true
  belongs_to :author,
             class_name: 'User',
             optional: true

  has_many :question_hashtags, dependent: :destroy
  has_many :hashtags, through: :question_hashtags

  validates :text, presence: true, length: { minimum: 1, maximum: 255 }

  validate :del, on: :destroy

  after_save_commit :create_hashtags

  # те вопросы, у которых поле "answer" не содержит nil
  scope :answered, -> { where.not(answer: nil) }
  # те вопросы, у которых поле "answer" содержит nil (не отвеченные)
  scope :unanswered, -> { where(answer: nil) }

  scope :sorted, -> { order(created_at: :desc) }

  scope :all_by_hashtags, lambda { |hashtags|
    questions = includes(:user)
    questions = if hashtags
                  # связка в SQL с таблице хэштегов, только если они существуют
                  questions.joins(:hashtags).where(hashtags: hashtags).preload(:hashtags)
                else
                  questions.includes(:question_hashtags, :hashtags)
                end
    # либо выбираем все вопросы
    questions.order(created_at: :desc)
  }

  private

  # выбираем любые 3 слова из вопроса в качестве хэштега,
  # содержащие от 4 до 20 букв
  def parse_hashtags(string)
    string.downcase.split
          .select { |i| i.chars.count.between?(4, 20) }
          .map { |i| i.delete('^a-zA-Zа-яА-Я-') }
          .uniq.sample(3)
  end

  # генератор хэштега (от анонима хэштеги не генерируюся)
  def create_hashtags
    return if author_id.nil?

    transaction do
      self.hashtags =
        parse_hashtags("#{text} #{answer}").map do |hashtag|
          Hashtag.create_or_find_by(text: "##{hashtag}")
        end
    end
  end

  def del
    return if hashtags.blank? || author_id.nil?

    self.hashtags = hashtags

    hashtags.destroy_all
  end
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

module Admin
  class UsersController < BaseController
    before_action :require_authentication
    before_action :set_user!, only: %i[edit update destroy upvote downvote]
    before_action :authorize_user!
    after_action :verify_authorized

    def upvote
      @user.increment!(:votes_count)
      redirect_to admin_users_path
    end

    def downvote
      @user.decrement!(:votes_count)
      redirect_to admin_users_path
    end

    # вытащим всех юзеров и разобъем их по страницам
    def index
      # научим наше приложение правильно отвечать на разные форматы запрошенные
      respond_to do |format|
        # описываем те форматы, на которые мы хотим отвечать
        format.html do
          @pagy, @users = pagy User.order(created_at: :desc)
          # render по умолчанию
        end

        format.zip do
          UserBulkExportJob.perform_later current_user
          # Задача поставлена в очередь на выполнение. Как только она завершится,
          # вы получите уведомление на email
          flash[:success] = t '.success'
          redirect_to admin_users_path
        end
      end
    end

    # открыть файл zip, вытащить оттуда файлы excel, каждый из низ обработать
    # и на основе него создать столько пользователей, сколько нужно с учетом валидаций.

    # Проверить, был ли передан архив. Если да, вызываем сервисный класс "UserBulkService",
    # передаем ему архив "params[:archive]".
    def edit; end

    def create
      if params[:archive].present?
        # UserBulkService.call params[:archive]
        #
        # Вместо вызова сервисного объекта с параметром "архив".
        # perform_later - поставить задачу в очередь и сделать в фоне
        # current_user - юзер, который инициировал задачу, и именно на его почту
        # будет выслана инфа о выполнении задачи
        UserBulkImportJob.perform_later(create_blob, current_user)
        flash[:success] = t('.success')
      end

      redirect_to admin_users_path
    end

    def update
      # вместо ".merge(skip_old_password: true" можно
      # @user.skip_old_password = true - только в админском контроллере
      if @user.update user_params
        flash[:success] = t '.success'
        redirect_to admin_users_path
      else
        render :edit
      end
    end

    def destroy
      @user.destroy
      flash[:success] = t '.success'
      redirect_to admin_users_path
    end

    private

    # создать новый файл в ActiveStorage
    def create_blob
      # открыть присланный временный файл
      file = File.open params[:archive]

      # "io" - input/output - содержимое файла, а в качестве имени файла - оригинальное имя архива
      Document.create!
      doc = Document.order('created_at desc').first
      doc.archive.attach io: file, filename: params[:archive].original_filename

      file.close

      # Вернем "key" - уникальный идентификатор загруженного файла в ActiveStorage. Этот ключ
      # будет храниться в одной из созданных таблиц
      doc.archive.url
    end

    def respond_with_zipped_users
      # Сгенерировать zip-файл, в котором будут находиться файлы Excel
      # OutputStream - архив, который мы будем пересылать юзеру в ответ на его запрос,
      # при этотом этот архив на диске у нас храниться не будет (временный архив).
      compressed_filestream = Zip::OutputStream.write_buffer do |zos|
        # Файлы будут создаваться для каждого юзера отдельно:
        User.order(created_at: :desc).each do |user|
          # Затем нам потребуется набрасывать в этот виртуальный архив какие-то файлы (записи).
          # Указываем после "zos.put_next_entry" имя файла, который хотим поместить в архив:
          zos.put_next_entry "user_#{user.id}.xlsx"
          # Сгенерировать excel-файл с помощью метода "render_to_string". Т.е. будем делать строку,
          # которую запишем с помощью "zos.print" в файл. Здесь:
          # handlers - обработчик используемого шаблона, на основе которого формируется конечный файл.
          # Обработчки наз. ":axlsx". template: 'admin/users/user' - представление, которое мы хотим
          # отрендерить и на основе которого сделать строку (представление будет располагаться в 'admin/users/user').
          # locals: { user: user } - локальная переменная, передаваемая представлению, которая будет
          # называться "user", и браться переменная будет из текущего "user". На основе данной переменной
          # сделаем файл Excel.
          zos.print render_to_string(
            layout: false, handlers: [:axlsx], formats: [:xlsx], template: 'admin/users/user', locals: { user: user }
          )
        end
      end

      # "Перемотать файл" - прочитать заново и отправить пользователю (rewind) архив "users.zip"
      # "send_data" - метод RoR
      compressed_filestream.rewind
      send_data compressed_filestream.read, filename: 'users.zip'
    end

    # найти юзера, которого есть желание отредактировать
    def set_user!
      @user = User.find params[:id]
    end

    # то, что мы хотим разрешить изменять в админке
    def user_params
      params.require(:user).permit(
        :email, :name, :username, :password, :password_confirmation, :role, :status
      ).merge(skip_old_password: true)
    end

    # м-д "authorize" возьмется из базового контроллера "BaseController"
    def authorize_user!
      # с наследованием
      authorize(@user || User)
      # без наследования
      # authorize([:admin, (@user || User)])
    end
  end
end

app/controllers/api/v1/users_controller.rb
# frozen_string_literal: true

module API
  module V1
    class UsersController < RootController
      def index
        @users = User.all

        success!(UserBlueprint.render_as_hash(@users))
      end
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# Контроллер, управляющий пользователями. Должен уметь:
#
#   1. Показывать страницу пользователя
#   2. Создавать новых пользователей
#   3. Позволять пользователю редактировать свою страницу
#
class UsersController < ApplicationController
  # записывать только уникальные показы
  impressionist actions: [:show],
                unique: %i[controller_name action_name session_hash]

  # пользователь в систему не вошел
  before_action :require_no_authentication, only: %i[new create]
  # пользователь в систему уже вошел
  before_action :require_authentication, only: %i[edit update destroy]
  before_action :set_user!, only: %i[show edit update destroy]

  # Проверяем имеет ли юзер доступ к экшену, делаем это для всех действий, кроме
  # :index, :new, :create, :show — к этим действиям есть доступ у всех, даже у
  # тех, у кого вообще нет аккаунта на нашем сайте.
  before_action :access_user, except: %i[index new create show]

  before_action :authorize_user!
  after_action :verify_authorized

  before_action :check_button, only: :show

  # Это действие отзывается, когда пользователь заходит по адресу /users
  def index
    @users = User.sorted

    @users = @users.decorate

    # Найти юзеров, зарегистрированных больше года назад, у которых на
    # странице ни одного вопроса
    # User.where('created_at < ?', 1.year.ago).without_questions

    @hashtags = Hashtag.with_questions
  end

  def show
    @user = @user.decorate

    # подсчет кол-ва переходов на страницу юзера ("датчик посещения")
    # @user.object.increment!(:impressions_count)
    @user.object.impressionist_count(message: 'get-request | users#show')

    # Достаем вопросы пользователя с помощью метода questions, который мы
    # объявили в модели User (has_many :questions), у результата возврата этого
    # метода вызываем метод order, который отсортирует вопросы по дате.
    @pagy, @questions = pagy @user.questions.includes(:author).sorted

    # Для формы нового вопроса, которая есть у нас на странице пользователя,
    # создаем болванку вопроса, вызывая метод build у результата вызова метода
    # @user.questions.
    @new_question = @user.questions.build

    # Количество вопросов
    @questions_count = @questions.count
    # Количество вопросов с ответами
    @answers_count = @questions.answered.count
    # Количество вопросов без ответа
    @unanswered_count = @questions.unanswered.count
  end

  # Действие create будет отзываться при POST-запросе по адресу /users из формы
  # нового пользователя, которая находится в шаблоне на странице /users/new.
  def new
    @user = User.new
  end

  def edit; end

  # Действие update будет отзываться при PUT-запросе из формы редактирования
  # пользователя, которая находится по адресу /users/:id, например,
  # /users/1
  #
  # Перед этим действием сработает before_action :load_user и в переменной @user
  # у нас будет лежать пользовать с нужным id равным params[:id].
  def create
    @user = User.new user_params

    if @user.save
      # Если удалось сохранить, отправляем пользователя на главную с сообщение, что
      # пользователь создан.
      # признак для юзера, что он в систему вошел
      sign_in @user
      WelcomeMailer.with(user: @user).welcome_email.deliver_later
      flash[:success] = t('.success', name: current_user.name_or_email)
      redirect_to root_path
    else
      # Если не удалось по какой-то причине сохранить пользователя, то рисуем
      # (обратите внимание, это не редирект), страницу new с формой
      # пользователя, который у нас лежит в переменной @user. В этом объекте
      # содержатся ошибки валидации, которые выведет шаблон формы.
      render :new
    end
  end

  # Это действие отзывается, когда пользователь заходит по адресу /users/:id,
  # например /users/1
  #
  # Перед этим действием сработает before_action :load_user и в переменной @user
  # у нас будет лежать пользовать с нужным id равным params[:id].
  def update
    # Аналогично create, мы получаем параметры нового (обновленного)
    # пользователя с помощью метода user_params, и пытаемся обновить @user с
    # этими значениями.
    if @user.update user_params
      flash[:success] = t '.success'
      redirect_to user_path(@user)
    else
      # Если не получилось, как и в create рисуем страницу редактирования
      # пользователя, на которой нам будет доступен объект @user, содержащий
      # информацию об ошибках валидации, которые отобразит форма.
      render :edit
    end
  end

  def destroy
    if @user.destroy
      flash[:success] = t '.success'
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def set_user!
    @user = User.find params[:id]
  end

  # Явно задаем список разрешенных параметров для модели User. Мы говорим, что
  # у хэша params должен быть ключ :user. Значением этого ключа может быть хэш с
  # ключами: :email, :password, :password_confirmation, :name, :username и
  # :avatar_url. Другие ключи будут отброшены.
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation,
                                 :name, :username, :old_password,
                                 :background_color, :api_token, :impressionist_count)
  end

  # Если загруженный из базы юзер и текущий залогиненный не совпадают — посылаем
  # его с помощью описанного в контроллере ApplicationController метода
  # reject_user.
  def access_user
    reject_user unless @user == current_user
  end

  def authorize_user!
    authorize(@user || User)
  end

  # проверка нажатия кнопки генерации токена на странице пользователя
  def check_button
    @user = User.find params[:id]

    if params[:pressing] && @user == current_user
      @user.generate_token
    elsif params[:pressing] && @user != current_user
      flash.now[:warning] = t '.show.forbidden'
    end
  end
end

app/helpers/admin/users_helper.rb
# frozen_string_literal: true

module Admin
  module UsersHelper
    def user_roles
      # возьмем ключи ролей { basic: 0, moderator: 1, admin: 2 }
      User.roles.keys.map do |role|
        # текст роли + id роли
        [t(role, scope: 'global.user.roles'), role]
      end
    end

    def user_statuses
      # возьмем ключи ролей { activated: 0, blocked: 1 }
      User.statuses.keys.map do |status|
        # текст статуса + id статуса
        [t(status, scope: 'global.user.statuses'), status]
      end
    end
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

require_relative 'internals'

module UsersHelper
  def inclination(amount, *words)
    prefix =
      if (11..14).cover?(amount % 100)
        words.empty? ? Box.many : " #{words[2]}"

      elsif amount % 10 == 1
        words.empty? ? Box.one : " #{words[0]}"

      elsif (2..4).cover?(amount % 10)
        words.empty? ? Box.several : " #{words[1]}"

      else
        words.empty? ? Box.many : " #{words[2]}"

      end

    amount.to_s + prefix
  end
end

app/views/users/edit.html.erb
<% provide :page_title, t('.form.title') %>

<%# Страница редактирования пользователя %>
<div class="container content-wrapper buffer-both">
<h1 class="title-medium"><%= t('.form.title') %></h1>

  <div class="column-1-2">
    <%# С помощью специального хелпера form_for мы делаем тег <form ...> %>
    <%# с нужными аттрибутами, после этого в переменной f будет специальный %>
    <%# объект (form builder object), вызывая методы которого мы можем %>
    <%# создавать теги для нужных нам полей формы. %>
      <%= form_for @user do |f| %>
      <%# Вывод ошибок валидации пользователя, если есть. Ошибки содержатся %>
      <%# в поле errors модели (в нашем случае @users). %>
      <%= render 'shared/errors', object: @user %>
      <%# С помощью методов label и text_field у объекта f мы создаем теги %>
      <%# <label ... > и <input type="text" ... > с нужными атрибуами %>
        <div class="form-field"> <%= f.label t('.form.username'), class: 'form-label' %>
        <%= f.text_field :username, class: 'form-text-field' %>
      </div>

      <%# Поступаем аналогично для других полей %>
      <div class="form-field">
        <%= f.label t('.form.name'), class: 'form-label' %>
        <%= f.text_field :name, class: 'form-text-field' %>
      </div>

      <div class="col-sm-2 col-form-label">
        <div class="form-field">
          <%= f.label :role, class:'form-label' %>
        </div>

          <%# readonly: true  - в это поле ввести ничего нельзя, да и в НЕадминском контроллере
          среди разрешенных параметров роли нет к тому же. Роль поменять не получится%>
        <div class="form-field">
          <%= f.text_field :role, value: t(@user.role, scope: 'global.user.roles'),
             class: 'form-control-plaintext form-control', readonly: true %>
        </div>
      </div>

      <div class="col-sm-2 col-form-label">
        <div class="form-field">
          <%= f.label :status, class:'form-label' %>
        </div>

        <%# readonly: true  - в это поле ввести ничего нельзя, да и в НЕадминском контроллере
        среди разрешенных параметров статуса нет к тому же. Статус поменять не получится %>
        <div class="form-field">
          <%= f.text_field :status, value: t(@user.status, scope: 'global.user.statuses'),
            class: 'form-control-plaintext form-control',readonly: true %>
        </div>
      </div>

      <% unless @user.api_token.blank?%>
        <div class="col-sm-2 col-form-label">
          <div class="form-field">
            <%= f.label :api_token, class:'form-label' %>
            <%= f.text_field :api_token, value: @user.api_token,
              class: 'form-control-plaintext form-control',readonly: true %>
          </div>
        </div>
      <% end %>

      <div class="form-field">
        <%= f.label t('.form.background_color'), class: 'form-label' %>
        <%= f.color_field :background_color, value: @user.bg_color %>
      </div>

      <div class="buffer-top-large buffer-bottom"><%= t('.form.message') %></div>

      <div class="form-field">
        <%= f.label t('.form.password'), class: 'form-label' %>
        <%= f.password_field :password, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label t('.form.password_confirmation'), class: 'form-label' %>
        <%= f.password_field :password_confirmation, class: 'form-text-field' %>
      </div>

      <% unless @user.new_record? %>
      <div class="form-field">
        <%= f.label t('.form.old_password'), class: 'form-label'%>
        <%= f.password_field :old_password, class: 'form-text-field' %>
      </div>
    <% end %>
  <% t_key = (@user.new_record? ? "register" : "save") %>
  <%= f.submit t(t_key, scope: 'users.global.forms'), class: 'button button-dark button-small' %>
    <%= link_to t('global.button.delete'), @user, method: :delete,
         class: 'button button-red button-small', data: {confirm: t('global.dialog.you_sure')}%>
  <% end %>

  <%# Подробнее про помощники для создания форм: %>
  <%# http://guides.rubyonrails.org/form_helpers.html %>
</div></div>

app/views/users/index.html.erb
<% provide :page_title %>

<% if policy(:user).index? %>
  <%# Этот шаблон отрисуется, когда пользователь захочет посмотреть список пользователей %>
  <div class="content-wrapper buffer-both text-center">
    <div class="buffer-both">
      <h1 class="title-medium"><%= t('.form.title') %></h1>
    </div>

    <%# Этот код выводит каждого пользователя в цикле %>
    <% @users.each do |user| %>
      <div class="users-list-item">
        <div class="user-image-div user-image-div-small">
          <%# link_to — генерирует ссылку %>
          <%# image_tag — генерирует картинку %>
          <%# user_avatar — достает из пользователя ссылку на картинку или подставляет дефолтную %>
          <%# Хелпер user_path(user) возвращает относительный путь %>
          <%# страницы пользователя, например /users/1 %>

          <% unless user.email == Dotenv.load('.env')['TEST_EMAIL'] %>
          <%= link_to user.gravatar(css_class: 'user-image'), user_path(user) %>
        <% else %>
          <%= link_to image_tag('Elizabeth.jpg', height: '90', width: '80',
                      class: 'menu_icon', alt: '[Foto]'), user_path(user) %>
        <% end %>

      </div>
    </div>
  <% end %>

  <section class="form-action">

      <%# отправляем форму на страницу "questions_path" - get-запрос%>
      <%= form_with url: questions_path , method: :get do |f| %>
        <div class="form-field">
          <%# {selected: params[:hashtag_ids]} - т.е. когда форма будет отправлена и страница перерисуется,
                          в этой форме выбирутся все те теги, которые выбраны для построения этого поиска.
                          required: true - чтоб эту форму нельзя было отправить пустой %>
          <%# ajax — асинхронный запрос отправляться сюда "/api/hashtags" и чтобы отсюда вытаскивать только те хэштеги,
                          которые подходят под критерии пользователя, т.е. исходя из того, что юзер напечатает %>
        <%= f.collection_select :hashtag_ids, (helper_hashtag(1) || []), :id, :text, {selected: params[:hashtag_ids]},
            multiple: true, required: true,
            class: 'js-multiple-select js-ajax-select w-100', data: {'ajax-url': '/api/hashtags'} %>
        </div>

        <%= f.submit t('global.button.search'), class: 'btn btn-primary btn-sm mb-3' %>

    <% end %>
  </section>

  </div>
<% end %>

app/views/users/show.html.erb
<% provide :page_title, @user.name_or_email  %>

<%# В шаблоне show мы пишем html-код для вывода внутреннего содержимого %>
<%# страницы пользователя, которая будет показана по адресу /users/1 %>

<%# Блок с информацией о пользователей %>
  <div class="user-header text-center" style="background: <%= @user.bg_color %>">

    <h1 class="title-medium">
        <%# Выводим имя пользователя %>
        <%= @user.name_or_email %>
    </h1>

    <div class="buffer-both">
      <%= link_to t('global.button.edit'), edit_user_path(@user) if current_user == @user  %>
    </div>

    <div class="buffer-both">
      <%= link_to "Фотографии", user_albums_path(@user) %>
    </div>

    <% if current_user == @user  %>
      <div class="buffer-both">
        <%= button_to "generate api_token", { action: "show", id: @user.id },
                class: 'button button-small button-dark', name: 'pressing',
                method: :get, data: { confirm: t('global.dialog.you_sure') },
                remote: true %>
      </div>
    <% end %>

    <div class="user-image-div">
       <% if @user.email != Dotenv.load('.env')['TEST_EMAIL'] %>
          <%= @user.gravatar %>
       <% else %>
          <%= image_tag 'Elizabeth.jpg', height: '115', width: '100',
                    class: 'menu_icon', alt: '[Foto]' %>
       <% end %>
    </div>


    <div class="user-details">

      <% unless current_user == @user  %>
        <div class="user-ask-button container text-center">
          <%= link_to t('global.button.ask'), user_path(@user), class: 'button button-light',
                      id: 'ask-button', data: {'bs-toggle': 'collapse'}  %>
        </div>
      <% end %>


      <div class="user-statistics container text-center">

        <div class="column-1-3">
          <%= inclination(@questions_count,
               t('.form.question'), t('.form.of_question'), t('.form.questions')) %>
        </div>

        <div class="column-1-3">
          <%= inclination(@answers_count,
             t('.form.answer'), t('.form.of_answer'), t('.form.answers')) %>
        </div>

        <div class="column-1-3">
        <% if I18n.locale.to_s == 'en' %>
          <%= inclination(@unanswered_count,
              "unanswered question", "unanswered questions", "unanswered questions") %>
        <% else %>
          <%= inclination(@unanswered_count,
              "вопрос", "вопроса", "вопросов") %>
              без ответа
        <% end %>
        </div>

      </div>
    </div>
</div>

<%# для нового вопроса question нет, поэтому передаем название политики %>
<% if policy(:question).new? %>
  <%# Блок с формой для задавания пользователю вопроса %>
  <%# Автор профиля не может создавать вопросы на своей странице %>
  <% unless current_user == @user %>
    <div class="user-question-form-div column-1-4 column-1-4-right" id='ask-form'>
      <div class="user-question-form buffer-both">
        <div class="form-field">
          <%# Мы используем хелпер form_for, принимающий на вход блок erb-кода, %>
          <%# в котором доступна переменная f, содержащая так называемый form %>
          <%# builder, с помощью которого можно делать поля формы для нового %>
          <%# вопроса. %>
            <%= form_for @new_question do |f| %>
            <%# С помощью объекта для создания полей формы, связанной с моделью %>
            <%# @new_question Мы создаем инпуты с нужными полями для формы, %>
            <%# значения будут подставлены rails автоматически. %>
              <%= f.hidden_field :user_id %>
              <div class="form-field">
                  <%= f.label t('.form.your_question', username: @user.username), class: 'form-label' %>
                  <%= f.text_area :text, class: 'form-textarea' %>
              </div>

              <%= recaptcha_tags size: 'compact' unless current_user.present?%>

              <div class="form-action">
                  <%= submit_tag t('.form.ask_question'), class: 'button button-small button-dark' %>
              </div>
            <% end %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

<%# Блок со списком вопросов к пользователю %>
<div class="column-3-4">
  <div class="user-questions buffer-both">
    <div class="questions-list">
      <%# Обратите внимание, как мы делаем цикл по всем вопросам, точно %>
      <%# также, как мы делали циклы в ruby %>

        <%# данная навигация показывается в том случае, если количество страниц больше 1 %>
        <%= pagination @pagy %>

        <% @questions.includes([:question_hashtags, :hashtags]).each do |question| %>
             <%# Мы рисуем здесь для кажого вопроса в списке вопросов фрагмент %>
             <%# (паршал), передавая в него текущий вопрос. Это очень похоже на %>
             <%# вызов метода в ruby %>
             <%= render partial: 'questions/question', object: question %>
        <% end %>

      <%= pagination @pagy %>
    </div>
  </div>
</div>