config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

# класс "Ограничение". М-д "matches" принимает запрос, который был отправлен
# на адрес '/admin/users'. Приходит на этот адрес запрос, перенаправлем в AdminConstraint
# проверку, читаем запрос, смотрим, от кого он и решаем: пускать или нет.
# "user_id" - помещен либо в сессию, либо в зашифрованные куки если юзер поставил галочку
# "запомнить меня" (см. authentication.rb)
# request.cookie_jar.encrypted[:user_id] - дешифровка куки
class AdminConstraint
  def matches?(request)
    user_id = request.session[:user_id] || request.cookie_jar.encrypted[:user_id]
    # является ли найденный юзер админом (если юзер найден)
    User.find_by(id: user_id)&.admin_role?
  end
end

Rails.application.routes.draw do
  # Смонтировать маршрут Sidekiq::Web , по какому адресу он будет доступен ('/sidekiq'),
  # т.е. подрубаем интерфейс sidekiq по адресу '/sidekiq' (http://127.0.0.1:3000/sidekiq)
  mount Sidekiq::Web => '/sidekiq', constraints: AdminConstraint.new

  resources :hashtags, only: :show, param: :text

  # API V1 (версия 1) routes
  namespace :api do
    namespace :v1 do
      resources :users, only: [], param: :username do
        resources :questions, only: :index
        resources :albums, except: %i[edit new]
      end

      resources :hashtags, only: :index
      resources :users, only: :index
    end
  end

  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    # Для любого юзера будет только одна сессия регистрации (!)
    resource :session, only: %i[new create destroy]

    resources :users do
      resources :albums do
        member do
          delete :delete_album_photos
        end
      end
    end

    resource :password_reset, only: %i[new create edit update]

    # Со страницы юзера будет отправляться форма на создание вопроса
    resources :questions, except: %i[show new]

    root 'users#index'

    # не будет существовать тогда маршрута для всех, кроме админа. Закрывается
    # доступ к пространству маршрутов admin
    namespace :admin do
      constraints(AdminConstraint.new) do
        resources :users, except: %i[new] do
          get :upvote, on: :member
          get :downvote, on: :member
        end
      end
    end

    # Синонимы путей — в дополнение к созданным в ресурсах выше.
    # get 'sign_up' => 'users#new'
    # get 'log_out' => 'sessions#destroy'
    # get 'log_in' => 'sessions#new'
  end
end

app/views/shared/_errors.html.erb
<% if object&.errors&.full_messages.any? %>
  <div class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_menu.html.erb
<header class="header-nav">
	<div class="container">
		<nav class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
			<ul class="nav col-12 col-lg-auto mb-2 mb-md-1">
				<li class="dropdown">
					<%= link_to '#', class: 'nav-link px-2 dropdown-toggle text-white',
										data: {"bs-toggle": 'dropdown'} do %>
							<%= tag.div '', class: "flag #{I18n.locale}-flag mt-1" %>
						<%= t I18n.locale %>
					<% end %>

			    <ul class="dropdown-menu">
						<% I18n.available_locales.each do |locale| %>
							<li>
								<% if I18n.locale == locale %>
									<%= tag.span t(locale), class: 'dropdown-item' %>
								<% else %>
									<%= link_to t(locale), url_for(params_plus(locale: locale)),
											class: 'dropdown-item' %>
								<% end %>
					    </li>
				    <% end %>
			    </ul>
		    </li>
		  </ul>
	  </nav>
	</div>
</header>

<div class="header">

	<div class="header-logo">
		<a class="title-small">$:</a>
		<%= content_tag(:a, number_to_currency(current_rate[0]), class: "title-small") %>
		<br>
		<a class="title-small">€:</a>
		<%= content_tag(:a, number_to_currency(current_rate[1]), class: "title-small") %>
	</div>

	<div class="container">

		<div class="header-logo">
			<h1 class="header-title">
				<%= link_to t('menu.home'), root_path %>
			</h1>
		</div>

	<%# Выводим в хэдере информацию для логина/авторизации/регистрации %>
		<div class="header-nav">

      <%# Кто может считывать список всех юзеров? Только админ!
      передаем namespace (:admin) и название той политики, которую считываем (:user)%>
      <% if policy([:admin, :user]).index? %>
      <%# ссылка на админский маршрут со списком юзеров %>
        <%= link_to t('menu.users'), admin_users_path,
              class: 'button button-light button-small'%>
			<% end %>
			<%# Если есть текущий юзер (значит он залогинен) %>
			<% if user_signed_in? %>
				<%# Даем ссылки на его профиль и на логаут %>
				<%= link_to "@#{current_user.username}", user_path(current_user) %>
				|
				<%= link_to t('menu.sign_out'), session_path, data: { method: :delete } %>
			<% else %>
				<%# Если нету — ссылки на регистрацию и логин %>
			<%= link_to t('menu.sign_up'), new_user_path,
					class: 'button button-light button-small' %>
				<%= link_to t('menu.sign_in'), new_session_path,
					class: 'button button-light button-small' %>
			<% end %>
		</div>
	</div>
</div>