config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

# класс "Ограничение". М-д "matches" принимает запрос, который был отправлен
# на адрес '/admin/users'. Приходит на этот адрес запрос, перенаправлем в AdminConstraint
# проверку, читаем запрос, смотрим, от кого он и решаем: пускать или нет.
# "user_id" - помещен либо в сессию, либо в зашифрованные куки если юзер поставил галочку
# "запомнить меня" (см. authentication.rb)
# request.cookie_jar.encrypted[:user_id] - дешифровка куки
class AdminConstraint
  def matches?(request)
    user_id = request.session[:user_id] || request.cookie_jar.encrypted[:user_id]
    # является ли найденный юзер админом (если юзер найден)
    User.find_by(id: user_id)&.admin_role?
  end
end

Rails.application.routes.draw do
  # Смонтировать маршрут Sidekiq::Web , по какому адресу он будет доступен ('/sidekiq'),
  # т.е. подрубаем интерфейс sidekiq по адресу '/sidekiq' (http://127.0.0.1:3000/sidekiq)
  mount Sidekiq::Web => '/sidekiq', constraints: AdminConstraint.new

  resources :hashtags, only: :show, param: :text

  # API V1 (версия 1) routes
  namespace :api do
    namespace :v1 do
      resources :users, only: [], param: :username do
        resources :questions, only: :index
        resources :albums, except: %i[edit new]
      end

      resources :hashtags, only: :index
      resources :users, only: :index
    end
  end

  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    # Для любого юзера будет только одна сессия регистрации (!)
    resource :session, only: %i[new create destroy]

    resources :users do
      resources :albums do
        member do
          delete :delete_album_photos
        end
      end
    end

    resource :password_reset, only: %i[new create edit update]

    # Со страницы юзера будет отправляться форма на создание вопроса
    resources :questions, except: %i[show new]

    root 'users#index'

    # не будет существовать тогда маршрута для всех, кроме админа. Закрывается
    # доступ к пространству маршрутов admin
    namespace :admin do
      constraints(AdminConstraint.new) do
        resources :users, except: %i[new] do
          get :upvote, on: :member
          get :downvote, on: :member
        end
      end
    end

    # Синонимы путей — в дополнение к созданным в ресурсах выше.
    # get 'sign_up' => 'users#new'
    # get 'log_out' => 'sessions#destroy'
    # get 'log_in' => 'sessions#new'
  end
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

module Admin
  class UsersController < BaseController
    before_action :require_authentication
    before_action :set_user!, only: %i[edit update destroy upvote downvote]
    before_action :authorize_user!
    after_action :verify_authorized

    def upvote
      @user.increment!(:votes_count)
      redirect_to admin_users_path
    end

    def downvote
      @user.decrement!(:votes_count)
      redirect_to admin_users_path
    end

    # вытащим всех юзеров и разобъем их по страницам
    def index
      # научим наше приложение правильно отвечать на разные форматы запрошенные
      respond_to do |format|
        # описываем те форматы, на которые мы хотим отвечать
        format.html do
          @pagy, @users = pagy User.order(created_at: :desc)
          # render по умолчанию
        end

        format.zip do
          UserBulkExportJob.perform_later current_user
          # Задача поставлена в очередь на выполнение. Как только она завершится,
          # вы получите уведомление на email
          flash[:success] = t '.success'
          redirect_to admin_users_path
        end
      end
    end

    # открыть файл zip, вытащить оттуда файлы excel, каждый из низ обработать
    # и на основе него создать столько пользователей, сколько нужно с учетом валидаций.

    # Проверить, был ли передан архив. Если да, вызываем сервисный класс "UserBulkService",
    # передаем ему архив "params[:archive]".
    def edit; end

    def create
      if params[:archive].present?
        # UserBulkService.call params[:archive]
        #
        # Вместо вызова сервисного объекта с параметром "архив".
        # perform_later - поставить задачу в очередь и сделать в фоне
        # current_user - юзер, который инициировал задачу, и именно на его почту
        # будет выслана инфа о выполнении задачи
        UserBulkImportJob.perform_later(create_blob, current_user)
        flash[:success] = t('.success')
      end

      redirect_to admin_users_path
    end

    def update
      # вместо ".merge(skip_old_password: true" можно
      # @user.skip_old_password = true - только в админском контроллере
      if @user.update user_params
        flash[:success] = t '.success'
        redirect_to admin_users_path
      else
        render :edit
      end
    end

    def destroy
      @user.destroy
      flash[:success] = t '.success'
      redirect_to admin_users_path
    end

    private

    # создать новый файл в ActiveStorage
    def create_blob
      # открыть присланный временный файл
      file = File.open params[:archive]

      # "io" - input/output - содержимое файла, а в качестве имени файла - оригинальное имя архива
      Document.create!
      doc = Document.order('created_at desc').first
      doc.archive.attach io: file, filename: params[:archive].original_filename

      file.close

      # Вернем "key" - уникальный идентификатор загруженного файла в ActiveStorage. Этот ключ
      # будет храниться в одной из созданных таблиц
      doc.archive.url
    end

    def respond_with_zipped_users
      # Сгенерировать zip-файл, в котором будут находиться файлы Excel
      # OutputStream - архив, который мы будем пересылать юзеру в ответ на его запрос,
      # при этотом этот архив на диске у нас храниться не будет (временный архив).
      compressed_filestream = Zip::OutputStream.write_buffer do |zos|
        # Файлы будут создаваться для каждого юзера отдельно:
        User.order(created_at: :desc).each do |user|
          # Затем нам потребуется набрасывать в этот виртуальный архив какие-то файлы (записи).
          # Указываем после "zos.put_next_entry" имя файла, который хотим поместить в архив:
          zos.put_next_entry "user_#{user.id}.xlsx"
          # Сгенерировать excel-файл с помощью метода "render_to_string". Т.е. будем делать строку,
          # которую запишем с помощью "zos.print" в файл. Здесь:
          # handlers - обработчик используемого шаблона, на основе которого формируется конечный файл.
          # Обработчки наз. ":axlsx". template: 'admin/users/user' - представление, которое мы хотим
          # отрендерить и на основе которого сделать строку (представление будет располагаться в 'admin/users/user').
          # locals: { user: user } - локальная переменная, передаваемая представлению, которая будет
          # называться "user", и браться переменная будет из текущего "user". На основе данной переменной
          # сделаем файл Excel.
          zos.print render_to_string(
            layout: false, handlers: [:axlsx], formats: [:xlsx], template: 'admin/users/user', locals: { user: user }
          )
        end
      end

      # "Перемотать файл" - прочитать заново и отправить пользователю (rewind) архив "users.zip"
      # "send_data" - метод RoR
      compressed_filestream.rewind
      send_data compressed_filestream.read, filename: 'users.zip'
    end

    # найти юзера, которого есть желание отредактировать
    def set_user!
      @user = User.find params[:id]
    end

    # то, что мы хотим разрешить изменять в админке
    def user_params
      params.require(:user).permit(
        :email, :name, :username, :password, :password_confirmation, :role, :status
      ).merge(skip_old_password: true)
    end

    # м-д "authorize" возьмется из базового контроллера "BaseController"
    def authorize_user!
      # с наследованием
      authorize(@user || User)
      # без наследования
      # authorize([:admin, (@user || User)])
    end
  end
end

app/controllers/api/v1/users_controller.rb
# frozen_string_literal: true

module API
  module V1
    class UsersController < RootController
      def index
        @users = User.all

        success!(UserBlueprint.render_as_hash(@users))
      end
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# Контроллер, управляющий пользователями. Должен уметь:
#
#   1. Показывать страницу пользователя
#   2. Создавать новых пользователей
#   3. Позволять пользователю редактировать свою страницу
#
class UsersController < ApplicationController
  # записывать только уникальные показы
  impressionist actions: [:show],
                unique: %i[controller_name action_name session_hash]

  # пользователь в систему не вошел
  before_action :require_no_authentication, only: %i[new create]
  # пользователь в систему уже вошел
  before_action :require_authentication, only: %i[edit update destroy]
  before_action :set_user!, only: %i[show edit update destroy]

  # Проверяем имеет ли юзер доступ к экшену, делаем это для всех действий, кроме
  # :index, :new, :create, :show — к этим действиям есть доступ у всех, даже у
  # тех, у кого вообще нет аккаунта на нашем сайте.
  before_action :access_user, except: %i[index new create show]

  before_action :authorize_user!
  after_action :verify_authorized

  before_action :check_button, only: :show

  # Это действие отзывается, когда пользователь заходит по адресу /users
  def index
    @users = User.sorted

    @users = @users.decorate

    # Найти юзеров, зарегистрированных больше года назад, у которых на
    # странице ни одного вопроса
    # User.where('created_at < ?', 1.year.ago).without_questions

    @hashtags = Hashtag.with_questions
  end

  def show
    @user = @user.decorate

    # подсчет кол-ва переходов на страницу юзера ("датчик посещения")
    # @user.object.increment!(:impressions_count)
    @user.object.impressionist_count(message: 'get-request | users#show')

    # Достаем вопросы пользователя с помощью метода questions, который мы
    # объявили в модели User (has_many :questions), у результата возврата этого
    # метода вызываем метод order, который отсортирует вопросы по дате.
    @pagy, @questions = pagy @user.questions.includes(:author).sorted

    # Для формы нового вопроса, которая есть у нас на странице пользователя,
    # создаем болванку вопроса, вызывая метод build у результата вызова метода
    # @user.questions.
    @new_question = @user.questions.build

    # Количество вопросов
    @questions_count = @questions.count
    # Количество вопросов с ответами
    @answers_count = @questions.answered.count
    # Количество вопросов без ответа
    @unanswered_count = @questions.unanswered.count
  end

  # Действие create будет отзываться при POST-запросе по адресу /users из формы
  # нового пользователя, которая находится в шаблоне на странице /users/new.
  def new
    @user = User.new
  end

  def edit; end

  # Действие update будет отзываться при PUT-запросе из формы редактирования
  # пользователя, которая находится по адресу /users/:id, например,
  # /users/1
  #
  # Перед этим действием сработает before_action :load_user и в переменной @user
  # у нас будет лежать пользовать с нужным id равным params[:id].
  def create
    @user = User.new user_params

    if @user.save
      # Если удалось сохранить, отправляем пользователя на главную с сообщение, что
      # пользователь создан.
      # признак для юзера, что он в систему вошел
      sign_in @user
      WelcomeMailer.with(user: @user).welcome_email.deliver_later
      flash[:success] = t('.success', name: current_user.name_or_email)
      redirect_to root_path
    else
      # Если не удалось по какой-то причине сохранить пользователя, то рисуем
      # (обратите внимание, это не редирект), страницу new с формой
      # пользователя, который у нас лежит в переменной @user. В этом объекте
      # содержатся ошибки валидации, которые выведет шаблон формы.
      render :new
    end
  end

  # Это действие отзывается, когда пользователь заходит по адресу /users/:id,
  # например /users/1
  #
  # Перед этим действием сработает before_action :load_user и в переменной @user
  # у нас будет лежать пользовать с нужным id равным params[:id].
  def update
    # Аналогично create, мы получаем параметры нового (обновленного)
    # пользователя с помощью метода user_params, и пытаемся обновить @user с
    # этими значениями.
    if @user.update user_params
      flash[:success] = t '.success'
      redirect_to user_path(@user)
    else
      # Если не получилось, как и в create рисуем страницу редактирования
      # пользователя, на которой нам будет доступен объект @user, содержащий
      # информацию об ошибках валидации, которые отобразит форма.
      render :edit
    end
  end

  def destroy
    if @user.destroy
      flash[:success] = t '.success'
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def set_user!
    @user = User.find params[:id]
  end

  # Явно задаем список разрешенных параметров для модели User. Мы говорим, что
  # у хэша params должен быть ключ :user. Значением этого ключа может быть хэш с
  # ключами: :email, :password, :password_confirmation, :name, :username и
  # :avatar_url. Другие ключи будут отброшены.
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation,
                                 :name, :username, :old_password,
                                 :background_color, :api_token, :impressionist_count)
  end

  # Если загруженный из базы юзер и текущий залогиненный не совпадают — посылаем
  # его с помощью описанного в контроллере ApplicationController метода
  # reject_user.
  def access_user
    reject_user unless @user == current_user
  end

  def authorize_user!
    authorize(@user || User)
  end

  # проверка нажатия кнопки генерации токена на странице пользователя
  def check_button
    @user = User.find params[:id]

    if params[:pressing] && @user == current_user
      @user.generate_token
    elsif params[:pressing] && @user != current_user
      flash.now[:warning] = t '.show.forbidden'
    end
  end
end

app/helpers/admin/users_helper.rb
# frozen_string_literal: true

module Admin
  module UsersHelper
    def user_roles
      # возьмем ключи ролей { basic: 0, moderator: 1, admin: 2 }
      User.roles.keys.map do |role|
        # текст роли + id роли
        [t(role, scope: 'global.user.roles'), role]
      end
    end

    def user_statuses
      # возьмем ключи ролей { activated: 0, blocked: 1 }
      User.statuses.keys.map do |status|
        # текст статуса + id статуса
        [t(status, scope: 'global.user.statuses'), status]
      end
    end
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

require_relative 'internals'

module UsersHelper
  def inclination(amount, *words)
    prefix =
      if (11..14).cover?(amount % 100)
        words.empty? ? Box.many : " #{words[2]}"

      elsif amount % 10 == 1
        words.empty? ? Box.one : " #{words[0]}"

      elsif (2..4).cover?(amount % 10)
        words.empty? ? Box.several : " #{words[1]}"

      else
        words.empty? ? Box.many : " #{words[2]}"

      end

    amount.to_s + prefix
  end
end

app/views/admin/users/_form.html.erb
<%= render 'shared/errors', object: user %>
<%= form_with model: [:admin, user] do |f| %>
  <div class="col-sm-2 col-form-label">
    <div class="form-field">
      <%= f.label :email, class: 'form-label' %>
    </div>

    <div class="form-field">
        <%= f.email_field :email, class: 'form-text-field', readonly: true %>
    </div>
  </div>

  <div class="col-sm-2 col-form-label">
    <div class="form-field">
      <%= f.label :name, class: 'form-label' %>
    </div>

    <div class="form-field">
      <%= f.text_field :name, class: 'form-text-field' %>
    </div>
  </div>

  <div class="col-sm-2 col-form-label">
    <div class="form-field">
      <%= f.label :username, class: 'form-label' %>
    </div>

    <div class="form-field">
      <%= f.text_field :username, class: 'form-text-field' %>
    </div>
  </div>

  <div class="col-sm-2 col-form-label">
    <div class="form-field">
      <%= f.label :role, class: 'form-label' %>
    </div>

    <%# выведутся все роли, которые поддерживаются в приложении %>
    <div class="form-field">
      <%= f.select :role, user_roles, {}, class: 'form-select-text-select-field' %>
    </div>
  </div>

  <div class="col-sm-2 col-form-label">
    <div class="form-field">
      <%= f.label :status, class:'form-label' %>
    </div>

    <%# выведутся все статусы, которые поддерживаются в приложении %>
    <div class="form-field">
      <%= f.select :status, user_statuses, {}, class: 'form-select-text-select-field' %>
    </div>
  </div>

  <div class="col-sm-2 col-form-label">
    <div class="form-field">
      <%= f.label :password, class:'form-label' %>
    </div>

    <div class="form-field">
      <%= f.password_field :password, class: 'form-text-field'  %>
    </div>
  </div>

  <div class="col-sm-2 col-form-label">
    <div class="form-field">
      <%= f.label :password_confirmation, class:'form-label'  %>
    </div>

    <div class="form-field">
      <%= f.password_field :password_confirmation, class: 'form-text-field' %>
    </div>
  </div>

  <%# админы могут сами регистрировать новых юзеров %>
  <% t_key = (user.new_record? ? "register" : "save") %>
  <%= f.submit t(t_key, scope: 'users.global.forms'), class: 'button button-dark button-small' %>
<% end %>

app/views/admin/users/_user.html.erb
<tr align="center">
  <th scope="row"><%= user.id %></th>
  <td><%= user.name %></td>
  <td><%= user.username %></td>
  <td><%= user.email %></td>
  <td><%= user.role %></td>
  <td><%= l user.created_at, format: :short %></td>
  <td><%= user.impressions_count %></td>
  <td><%= user.votes_count %> &nbsp;
       <%= link_to '+', upvote_admin_user_path(user), class: "text-info" %>
       /
       <%= link_to '-', downvote_admin_user_path(user), class: "text-info" %>
  </td>
  <td>

    <div class="btn-group"></div>
      <%= link_to t('global.link.edit'), edit_admin_user_path(user), class: 'button button-dark button-small' %>
    </div>
    <div class="btn-group">
      <%= link_to t('global.link.delete'), admin_user_path(user), class: 'button submit-danger button-small',
          data: {method: :delete, confirm: t('global.dialog.you_sure')} %>
    </div>

  </td>
</tr>

app/views/admin/users/edit.html.erb
<% provide :page_title, t('.title') %>

<div class="container content-wrapper buffer-both">
<h1 class="title-small"><%= t('.title') %></h1>

<%= render 'form', user: @user %>
</div>

app/views/admin/users/index.html.erb
<% provide :page_title, t('.title') %>

<div class="container content-wrapper buffer-both">
    <h1 class="title-small"><%= t '.title' %></h1>

    <%# загрузить данные в формате XLSX, причем они будут в формате архива %>
    <div class="form-field">
      <div class="btn-group">
        <%= link_to t('.download_zipped'), admin_users_path(format: :zip),
        # Действительно ли вы хотите запустить эту задачу на выполнение
              class: 'button button-small button-dark', data: {confirm: t('global.dialog.you_sure')} %>
      </div>
    </div>

    <%= pagination @pagy %>
    <section class="form-action">
      <% scope = 'activerecord.attributes.user' %>
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col"><%= t 'name', scope: scope %></th>
            <th scope="col"><%= t 'username', scope: scope %></th>
            <th scope="col"><%= t 'email', scope: scope %></th>
            <th scope="col"><%= t 'role', scope: scope %></th>
            <th scope="col"><%= t 'created_at', scope: scope %></th>
            <th scope="col"><%= t 'rating_real', scope: scope %></th>
            <th scope="col"><%= t 'rating_admin', scope: scope %></th>
            <th scope="col"><%= t 'doing', scope: scope %></th>
          </tr>
        </thead>
        <tbody>
          <%= render @users %>
        </tbody>
      </table>
    </section>

    <%= pagination @pagy %>
    <div class="buffer-both">
    <%# Можно загружать юзеров из файла XLSX<%>
    <h2 class="title-small"><%= t '.upload_zipped' %></h2>

    <%# url будем вести на "admin_users_path" - это метод "create" %>
    <%= form_with url: admin_users_path do |f| %>
      <div class="form-field">
        <div class="col-sm-2 col-form-label">
          <%= f.label :archive, t('.upload_form.archive') %>
        </div>

        <div class="form-field">
          <%# поле для загрузки файла %>
          <%# :archive - здесь будет располагаться путь к архиву %>
        <%= f.file_field :archive, class: 'form-text-field' %>
      </div>
      </div>

    <%= f.submit t('.upload_form.submit'), class: 'button button-small button-dark' %>
  <% end %>
  </div>
</div>